services:
  server:
    build: ./server
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=main.py
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - PUBLIC_API_URL=http://server:5000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
  python_packages:
